[package]
name = "mcap2arrow-arrow"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
include.workspace = true

[dependencies]
mcap2arrow-core.workspace = true
arrow.workspace = true
