[[pre-release-replacements]]
file = "README.md"
search = "(mcap2arrow.*) = \\{ version = \"[0-9\\.]+\"(.*) }"
replace = "$1 = { version = \"{{version}}\"$2 }"
min = 0

[[pre-release-replacements]]
file = "README.md"
search = "(mcap2arrow.*) = \"[0-9\\.]+\""
replace = "$1 = \"{{version}}\""
min = 0
