[package]
name = "mcap2arrow-ros2-common"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
mcap2arrow-core.workspace = true
thiserror.workspace = true
bytes = "1.11.1"
