[package]
name = "mcap2arrow-ros2idl"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
mcap2arrow-core.workspace = true
mcap2arrow-ros2-common.workspace = true
thiserror.workspace = true
nom = "7.1.3"
