[package]
name = "mcap2arrow-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
include.workspace = true

[dependencies]
anyhow.workspace = true
mcap.workspace = true
memmap2.workspace = true
thiserror.workspace = true
